# Generated by Django 5.1.6 on 2025-02-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_username'),
        ('blog', '0002_remove_postagem_categorias_remove_comentario_autor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
