# Generated by Django 5.1.5 on 2025-03-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagens',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
